(function () {
    this.pageConfig = {
        imgs: [
        	{title: "游戏UI",desc: null,url: "../imgs/Portfolio/1_GameUI/1.jpg"},
        	{title: "游戏UI",desc: null,url: "../imgs/Portfolio/1_GameUI/2.jpg"},
        	{title: "游戏UI",desc: null,url: "../imgs/Portfolio/1_GameUI/3.jpg"},
        	{title: "游戏UI",desc: null,url: "../imgs/Portfolio/1_GameUI/4.jpg"},
        	{title: "游戏UI",desc: null,url: "../imgs/Portfolio/1_GameUI/5.jpg"},
        	{title: "游戏UI",desc: null,url: "../imgs/Portfolio/1_GameUI/6.jpg"},
        	{title: "游戏UI",desc: null,url: "../imgs/Portfolio/1_GameUI/7.jpg"},
        	{title: "游戏UI",desc: null,url: "../imgs/Portfolio/1_GameUI/8.jpg"},
        	{title: "游戏UI",desc: null,url: "../imgs/Portfolio/1_GameUI/9.jpg"},
        	{title: "游戏UI",desc: null,url: "../imgs/Portfolio/1_GameUI/10.jpg"},
        	{title: "游戏UI",desc: null,url: "../imgs/Portfolio/1_GameUI/11.jpg"},
        	{title: "游戏UI",desc: null,url: "../imgs/Portfolio/1_GameUI/12.jpg"},
        	{title: "游戏UI",desc: null,url: "../imgs/Portfolio/1_GameUI/13.jpg"},
        	{title: "游戏UI",desc: null,url: "../imgs/Portfolio/1_GameUI/14.jpg"},
        	{title: "游戏UI",desc: null,url: "../imgs/Portfolio/1_GameUI/15.jpg"},
        	{title: "游戏UI",desc: null,url: "../imgs/Portfolio/1_GameUI/16.jpg"},
        	{title: "原创作品",desc: null,url: "../imgs/Portfolio/2_Original/1.jpg"},
        	{title: "原创作品",desc: null,url: "../imgs/Portfolio/2_Original/2.jpg"},
        	{title: "原创作品",desc: null,url: "../imgs/Portfolio/2_Original/3.jpg"},
        	{title: "原创作品",desc: null,url: "../imgs/Portfolio/2_Original/4.jpg"},
        	{title: "原创作品",desc: null,url: "../imgs/Portfolio/2_Original/5.jpg"},
        	{title: "原创作品",desc: null,url: "../imgs/Portfolio/2_Original/6.jpg"},
        	{title: "原创作品",desc: null,url: "../imgs/Portfolio/2_Original/7.jpg"},
        	{title: "原创作品",desc: null,url: "../imgs/Portfolio/2_Original/8.jpg"},
        	{title: "原创作品",desc: null,url: "../imgs/Portfolio/2_Original/9.jpg"},
        	{title: "原创作品",desc: null,url: "../imgs/Portfolio/2_Original/10.jpg"},
        	{title: "原画临摹",desc: null,url: "../imgs/Portfolio/3_Copying/1.jpg"},
        	{title: "原画临摹",desc: null,url: "../imgs/Portfolio/3_Copying/2.jpg"},
        	{title: "原画临摹",desc: null,url: "../imgs/Portfolio/3_Copying/3.jpg"},
        	{title: "原画临摹",desc: null,url: "../imgs/Portfolio/3_Copying/4.jpg"},
        	{title: "原画临摹",desc: null,url: "../imgs/Portfolio/3_Copying/5.jpg"},
        	{title: "原画临摹",desc: null,url: "../imgs/Portfolio/3_Copying/6.jpg"},
        	{title: "原画临摹",desc: null,url: "../imgs/Portfolio/3_Copying/7.jpg"},
        	{title: "原画临摹",desc: null,url: "../imgs/Portfolio/3_Copying/8.jpg"},
        	{title: "Web App",desc: null,url: "../imgs/Portfolio/4_WebAPP/1.jpg"},
        	{title: "Web App",desc: null,url: "../imgs/Portfolio/4_WebAPP/2.jpg"},
        	{title: "Web App",desc: null,url: "../imgs/Portfolio/4_WebAPP/3.jpg"},
        	{title: "Web App",desc: null,url: "../imgs/Portfolio/4_WebAPP/4.jpg"}
           ]
    };
}).call(this);